---
- name: Create EC2 Instances
  hosts: localhost
  roles:
    - role: ec2instances
      vars:
        ec2instances_workshop_name: "{{ workshop_name }}"
        ec2instances_destroy: "{{ teardown_ec2 }}"
        ec2instances_kube_token: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_API_KEY') }}"
        ec2instances_kube_host: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_HOST') }}"
        ec2instances_kube_namespace: "{{ workshops_namespace }}"
        ec2instances_instance_count: "{{ workshop_instances }}"
        ec2instances_region: "{{ ec2_workshop_region }}"
  post_tasks:
    - name: Print outputs
      ansible.builtin.debug:
        var: terraform_outputs.outputs
      when: not teardown_ec2
    - name: Register artifacts
      ansible.builtin.set_stats:
        data:
          ec2_instances: "{{ terraform_outputs.outputs }}"
      when: not teardown_ec2

- name: Wait for instances to become available
  hosts: ec2instances
  gather_facts: false
  pre_tasks:
    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:

    - name: Gather facts for the first time
      ansible.builtin.setup:

- name: Complete setup on EC2 instances
  hosts: ec2instances
  roles:
    - role: ec2userdata
      become: true
      when: not teardown_ec2
