---
version: 1

  # build_arg_defaults:
  # EE_BASE_IMAGE: < BASE EE >

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools
    ADD terraform /sbin
  append:
    - RUN ls -la /etc

