---
- name: Create SNOs
  hosts: localhost
  roles:
    - role: sno
      vars:
        workshop_name: "{{ workshop_name }}"
        private_subnet: "{{ private_subnet }}"
        public_subnet: "{{ public_subnet }}"
        cluster_name: sno-lab-{{ workshop_name }}
        pull_secret: '{{ openshift_pull_secret }}'
        ssh_key: "{{ ssh_public_key }}"
        destroy: "{{ teardown_sno }}"
        instance_count: "{{ workshop_instances }}"
        workshops_namespace: "{{ workshops_namespace }}"

- name: Copy kubeconfig to each ec2 instance
  hosts: ec2instances
  roles:
    - role: kubeconfig
      vars:
        bucket_name: "exe-workshop-{{ workshop_name }}"
      when: not teardown
