---
- name: Create SNOs
  hosts: localhost
  roles:
    - role: sno
      vars:
        sno_workshop_name: "{{ workshop_name }}"
        sno_private_subnet: "{{ private_subnet }}"
        sno_public_subnet: "{{ public_subnet }}"
        sno_cluster_name: sno-lab-{{ workshop_name }}
        sno_pull_secret: '{{ openshift_pull_secret }}'
        sno_ssh_key: "{{ ssh_public_key }}"
        sno_destroy: "{{ teardown_sno }}"
        sno_instance_count: "{{ workshop_instances }}"
        sno_workshops_namespace: "{{ workshops_namespace }}"
        sno_region: "{{ sno_workshop_region }}"
- name: Copy kubeconfig to each ec2 instance
  hosts: ec2instances
  roles:
    - role: kubeconfig
      vars:
        kubeconfig_bucket_name: "exe-workshop-{{ workshop_name }}"
      when: not teardown
