---
apiVersion: v1
kind: Namespace
metadata:
  name: workshops
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workshop-sa
  namespace: workshops
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-workshop-sa
  namespace: workshops
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/attach"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["hive.openshift.io"]
  resources: ["clusterpools"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-workshop-sa-binding
  namespace: workshops
subjects:
- kind: ServiceAccount
  name: workshop-sa
  namespace: workshops
roleRef:
  kind: Role
  name: role-workshop-sa
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-installer
  namespace: workshops
subjects:
- kind: ServiceAccount
  name: workshop-sa
  namespace: workshops
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: cluster-installer
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-workshop-sa-namespace
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-workshop-sa-cluster-admin
subjects:
- kind: ServiceAccount
  name: workshop-sa
  namespace: workshops
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
