---
- name: Terraform outputs
  ansible.builtin.set_fact:
    ec2_instances: "{{ terraform_outputs.outputs }}"

- name: Write keyfile to disk
  ansible.builtin.copy:
    content: "{{ terraform_outputs.outputs.private_key_pem.value }}"
    dest: "/tmp/aws.pem"
    mode: "0600"

- name: Add hosts to inventory
  ansible.builtin.add_host:
    name: "{{ item.public_dns }}"
    groups: "ec2instances"
    ansible_host: "{{ item.public_ip }}"
    ansible_user: "ec2-user"
    ansible_ssh_private_key_file: "/tmp/aws.pem"
  loop: "{{ terraform_outputs.outputs.all.value }}"
