---
- name: Terraform outputs
  ansible.builtin.set_fact:
    ec2_instances: "{{ terraform_outputs.outputs }}"

- name: Write keyfile to disk
  ansible.builtin.copy:
    content: "{{ terraform_outputs.outputs.private_key_pem.value }}"
    dest: "/tmp/aws.pem"
    mode: "0600"

- name: Also write keyfile to k8s
  kubernetes.core.k8s:
    namespace: "{{ ec2instances_kube_namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "ec2-key-{{ ec2instances_workshop_name }}"
      type: Opaque
      data:
        aws.pem: "{{ terraform_outputs.outputs.private_key_pem.value | ansible.builtin.b64encode }}"

- name: Add hosts to inventory
  ansible.builtin.add_host:
    name: "{{ item.public_dns }}"
    groups: "ec2instances"
    ansible_host: "{{ item.public_ip }}"
    ansible_user: "ec2-user"
    ansible_ssh_private_key_file: "/tmp/aws.pem"
  loop: "{{ terraform_outputs.outputs.all.value }}"
