---
- name: Deploy or destroy the EC2 instances
  cloud.terraform.terraform:
    state: "{{ destroy | ternary('absent', 'present') }}"
    project_path: "{{ role_path }}/files/tf/"
    workspace: "{{ workshop_name }}"
    purge_workspace: "{{ destroy }}"
    force_init: true
    init_reconfigure: true
  environment:
    KUBE_TOKEN: "{{ kube_token }}"
    KUBE_HOST: "{{ kube_host }}"
    KUBE_NAMESPACE: "{{ kube_namespace }}"
    KUBE_IN_CLUSTER_CONFIG: "true"
    TF_VAR_workshop_name: "{{ workshop_name }}"
    TF_VAR_instance_count: "{{ instance_count }}"
    # TF_VAR_key_name: lay-key-{{ workshop_name }}
  register: terraform_outputs

- name: Additional setup upon create
  include_tasks:
    file: create.yml
  when: not destroy