---
- name: Download from S3 bucket
  amazon.aws.s3_object:
    bucket: "{{ bucket_name }}"
    region: "{{ region }}"
    object: "{{ item }}/metadata.json"
    dest: /tmp/installer/{{ item }}/metadata.json
    validate_certs: false
    mode: get
  ignore_errors: true
