---
- name: Deploy or destroy the shared VPC
  community.general.terraform:
    state: "{{ vpc_destroy | ternary('absent', 'present') }}"
    project_path: "{{ role_path }}/files/tf/"
    workspace: "{{ vpc_workshop_name }}"
    purge_workspace: "{{ vpc_destroy }}"
    force_init: true
    init_reconfigure: true
    complex_vars: true
    variables:
      aws_region: "{{ vpc_region }}"
  environment:
    KUBE_TOKEN: "{{ vpc_kube_token }}"
    KUBE_HOST: "{{ vpc_kube_host }}"
    KUBE_NAMESPACE: "{{ vpc_kube_namespace }}"
    KUBE_IN_CLUSTER_CONFIG: "true"
    TF_VAR_workshop_name: "{{ vpc_workshop_name }}"
  register: terraform_outputs

- name: Terraform outputs
  ansible.builtin.set_fact:
    vpc_public_subnet: "{{ terraform_outputs.outputs['sno-lab-vpc-subnet-public'].value[0] }}"
    vpc_private_subnet: "{{ terraform_outputs.outputs['sno-lab-vpc-subnet-private'].value[0] }}"
  when: not vpc_destroy
